// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameURL = "urls"

// URL mapped from table <urls>
type URL struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OriginalURL string    `gorm:"column:original_url;primaryKey" json:"original_url"`
	CreatedAt   time.Time `gorm:"column:created_at;primaryKey;default:now()" json:"created_at"`
	ShortCode   string    `gorm:"column:short_code" json:"short_code"`
}

// TableName URL's table name
func (*URL) TableName() string {
	return TableNameURL
}
